### ISSUE TITLE
Querying for content based on linked sub objects

### ISSUE THREAD

**Issue by davetao** [contentful/vault#100]
Hi.

We are starting to create some complex queries and was trying to figure out how we can search for content based on linked objects.

What sort of ORM model are you using and does it allow table joins? 
Is it possible to query for content using a SQL statement?

**Comment by davetao** [comment]
In the meantime, I know i can access the database directly via https://github.com/contentful/vault/issues/26 to write my complex queries

https://github.com/contentful/vault/issues/68#issuecomment-127175502 also mentions that we should be able to search via linked objects as well.

Do you have any approaches i should try in the meantime?

**Comment by tomxor** [comment]
> What sort of ORM model are you using and does it allow table joins? 

Vault uses its own implementation on top of SQLite. Link (relationships) resolution is a second step and the current state of the project is that queries do not contain information about linked resources.

> Is it possible to query for content using a SQL statement?

You can run queries directly on Vault's db using `Vault.getReadableDatabase()` (as you've mentioned), though this will return a normal `Cursor` and will not go through the processing pipeline of the library.

This feature is currently not supported. The best thing you could do right now is make queries directly on the db in order to figure out which ids you're after, then use the library on a second query with an `IN()` clause providing the desired ids. 

Once we figure out a plan for #68 this feature should be supported out-of-the-box and in a type-safe way.

**Comment by davetao** [comment]
Thanks @tomxor I thought that would be the case and best approach.
Thank you.

**Comment by davetao** [comment]
@tomxor just one more question in regards to this issue. I noticed that the database table names look nothing like the content type ids that they are referring to. 

Is there a way to identify these tables other than hard coding the table name?

Would it be more useful to the end user if we just used the content type id used in contentful? That way we can make it easier to identify.

**Comment by tomxor** [comment]
The table name is an internal string created by the library, it is basically a static prefix combined with a normalized base64 string of the content type id. Right now you can access the generated code directly in order to pull the name of the table:

```java
ModelHelper<Cat> helper = new Cat$$ModelHelper();
helper.getTableName(); // returns a string
```

I could possibly provide a convenience accessor for this property if that's of interest for anyone.
