### ISSUE TITLE
Database pre-seeding in gradle build script

### ISSUE THREAD

**Issue by barteo** [contentful/vault#102]
I'm wondering whether it would be technically possible to include task for gradle to prepare the database for asset folder during the app build process?

**Comment by tomxor** [comment]
What kind of benefits do you think of when you suggest plugging this into the build process? I mean, I understand the need to pull the db file easily, but I'm wondering how this relates to the build process itself.

**Comment by barteo** [comment]
Currently, I have to put initial db into asset folder manually every time I create build to distribute (test builds, beta, release). Having pre-seeding database created in build script I can make build process fully migrated to the build server. Db content changes in my case quite often and I need usually the latest version pre-seeded while making the builds.

**Comment by barteo** [comment]
Is there any recent progress in implementing this feature?

**Comment by mariobodemann** [comment]
Hello @barteo,

I do not have any progress for you, since it always depends on your specific use case. I can recommend reading [Executing commandline tasks in gradle](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Exec.html) and using a script like 

```
adb shell 'mkdir -p /sdcard/.contentful;
   run-as discovery.contentful cp databases/cfdiscovery.db /sdcard/.contentful';
adb pull /sdcard/.contentful app/src/main/assets
```

To copy the database file from an existing debug app, to you local git repository.
