### ISSUE TITLE
Download all available locales

### ISSUE THREAD

**Issue by vbohush** [contentful/vault#104]
Hi.

Is there a way to download content for all available locales without knowing those specifically?

Because now, when I add new locale to contentful, I should add it to annotation and release new build to Play Market.

**Comment by tomxor** [comment]
One approach to support this would be making the `locales` attribute optional, so when you want to explicitly define which locales to use:

```java
@Space(locales = { "a", "b", "c" } /* ... */)
```

otherwise for dynamic persistence just omit it.

However there are two issues to consider:

1. Whenever a new locale is introduced we must clear all the records in the db, and re-sync. Up to this point we've made it so the library **never** triggers synchronization on its own, and having this kind of behaviour would force us to either change that or leave the db in a state where there are no records, even though there used to be. I would personally prefer the latter.

2. Those who pre-seed the database with the `copyPath` attr will lose all their records for the same reasons.

cc @grncdr @neonichu

**Comment by vbohush** [comment]
In my case it's Ok. But in general it may be incorrect.

**Comment by grncdr** [comment]
Seems complex for the value it brings. I can see an argument _for_ making a new release to let your users know that you've added a new language. OTOH, I can see the appeal of controlling that experience 100% within your app. For the moment it's a low priority enhancement IMO.

**Comment by mariobodemann** [comment]
I closed this issue, since we are not having any plans to add a dynamic download of locales, ones a new one comes in. 

It is a rather specific use case, which should be handled on client side, not on SDK side.
