### ISSUE TITLE
Another model type

### ISSUE THREAD

**Issue by barteo** [contentful/vault#50]
How feasible would be to use a different model type in Vault? Instead of using:
```
@ContentType("cat")
public class Cat extends Resource {
  @Field public String name;
  @Field public Cat bestFriend;
  @Field public Asset image;
}
```
define model in a different way:
```
public class Entry extends Resource {
  Map<String, Object> fields;
}
```
What I'm going to achieve is to fetch different content type objects in a single line of code, e.g.:
```
vault.fetch(Entry.class).where("contentType = ?", "Cat")
```

**Comment by tomxor** [comment]
Having a generic container for fields eliminates any type-safety we get by defining them explicitly. In addition, right now each field corresponds to a column in the database and thus allows better indexing for queries by field values, whereas if we serialize an entire collection, making such queries won't be possible.

I am not completely against the idea of supporting queries for multiple content types, but am curious about your specific use-case.

If we do decide to support it, assuming the way to define models remains the same, perhaps we could do something like:
```java
fetch(Class<? extends Resource>... types)
```

then use it like this:
```java
List<Resource> result = vault.fetch(Cat.class, Dog.class)
    .where("age = ?", 5) // Assumes both Cat and Dog have "age" field
    .all();
```

This however imposes additional overhead on the caller, as one would have to iterate and check the content type in order to figure out what type of resource it is, e.g.:

```java
List<Resource> resources = vault.fetch(Cat.class, Dog.class, Asset.class).all();

for (Resource res : resources) {
  if ("content-type-dog".equals(res.contentType()) {
    // Dog
  } else if ("content-type-cat".equals(res.contentType()) {
    // Cat
  } else {
    // Asset
  }
}
```

It seems to me like a bigger mess than simply doing:
```java
List<Cat> cats = vault.fetch(Cat.class).all();
List<Dog> dogs = vault.fetch(Dog.class).all();
List<Asset> assets = vault.fetch(Asset.class).all();
```

**Comment by barteo** [comment]
The reason I'm considering a generic container for fields is that my mobile app doesn't know about content type at the apk build time. Therefore I cannot include classes like Cat and Dog into the project. The data model will be created/modified in Contentful web interface after the mobile app is published.

**Comment by tomxor** [comment]
The idea behind Vault was to generate code at compile-time which formulates a database schema that corresponds to your data model. If you are dealing with a case where the data model is unknown at compile-time, perhaps this project is not the best choice for your use-case.

As a workaround, you could use more generic content types, that share common/optional properties between your models, and anything which is dynamic can be kept as a raw JSON field, and included in your model:
```java
@Field Map dynamicStuff;
```

Otherwise, you can use the [contentful.java](https://github.com/contentful/contentful.java) library (v3 recently released) and fetch stuff from the Sync API directly, though you would have to deal with persistence on your own.
